project:
  type: website
  output-dir: docs

website:
  title: "Matteo Ventura"
  # Aggiungiamo un footer per dare un aspetto finito
  page-footer:
    left: "© 2026 Matteo Ventura"
    right: "Built with [Quarto](https://quarto.org/)"
  
  navbar:
    background: "#3c4a3e" 
    search: true        
    left:
      - href: index.qmd  
        text: Home
      - href: publications.qmd
        text: Publications
      - href: courses.qmd
        text: Courses
      - href: contacts.qmd
        text: Contacts
    right:
      - icon: github
        href: https://github.com/MatteoVentura

format:
  html:
    theme: 
      light: flatly
      dark: darkly     
    mainfont: "Inter, system-ui, sans-serif" 
    css: styles.css
    toc: true
    # SPOSTATO QUI E RINOMINATO:
    include-in-header:
      text: |
        <meta name="google-site-verification" content="C3ggHJs_ixVu-G17Z_vF1TG0r-XS1hQYsy6wOSJVfP8" />