project:
  type: website
  output-dir: docs

website:
  title: "Matteo Ventura"
  navbar:
    background: light
    left:
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: courses.qmd
        text: Courses
      - href: contacts.qmd
        text: Contacts
deployment:
    targets:
      - id: primary
        type: github-pages
        url: "https://MatteoVentura.github.io" # Assicurati che sia il tuo URL corretto di GitHub Pages
        branch: main # O gh-pages, a seconda della configurazione del tuo repository
        dir: docs # Corrisponde al tuo output-dir
        include:
          - "**/*.qmd"
          - "**/*.md"
        exclude:
          - "**/*_files"
          - "**/*_cache"
          - "**/_*"
          - "**/*.tmp"
          - "_site"
          - "**/draft: true" # Esclude i file con draft: true
format:
  html:
    theme: flatly
    mainfont: "Lucida Console"
    css: styles.css
    toc: false